using Domain.Enums;

namespace Domain.Models;

/// <summary>
/// The raw data payload packaged by CA for initial client bootstrapping.
/// </summary>
public class ClientProvisioningPayload
{
    public string FormatVersion { get; set; } = "1.0";
    public string BusinessCode { get; set; } = string.Empty;
    public string LegalName { get; set; } = string.Empty;
    public string TradeName { get; set; } = string.Empty;
    public string GSTIN { get; set; } = string.Empty;
    public string PAN { get; set; } = string.Empty;
    public BusinessType BusinessType { get; set; } = BusinessType.Retail;
    public string Address { get; set; } = string.Empty;
    public string City { get; set; } = string.Empty;
    public string State { get; set; } = string.Empty;
    public string Pincode { get; set; } = string.Empty;
    public string ContactPhone { get; set; } = string.Empty;
    public string ContactEmail { get; set; } = string.Empty;
    public string FinancialYearStart { get; set; } = "2026-04-01";
    public string InvoicePrefix { get; set; } = "INV-";
    
    // Initial Business Admin account credentials generated by CA
    public string AdminUsername { get; set; } = "admin";
    public string AdminFullName { get; set; } = "Business Administrator";
    public string AdminPasswordHash { get; set; } = string.Empty;
    public string AdminSalt { get; set; } = string.Empty;
    public string AdminTempPasswordPlain { get; set; } = string.Empty; // CA hands this to client

    // Initial License Configuration
    public SubscriptionTier SubscriptionPlan { get; set; } = SubscriptionTier.Basic;
    public DateTime IssuedDateUtc { get; set; } = DateTime.UtcNow;
    public DateTime ExpiryDateUtc { get; set; } = DateTime.UtcNow.AddMonths(1);
    public int GracePeriodDays { get; set; } = 7;
    public int MaxUsers { get; set; } = 5;
    public int MaxBranches { get; set; } = 1;
    public int MaxProducts { get; set; } = 10000;
    public List<string> EnabledModules { get; set; } = new() { "Billing", "Inventory", "GSTReports", "RackManagement" };
}

/// <summary>
/// The cryptographically signed and encrypted container (.key, .lic, .enc, .pkg)
/// </summary>
public class EncryptedPackageEnvelope
{
    public string PackageType { get; set; } = string.Empty; // "DATA_KEY", "LICENSE", "AUDIT_EXPORT", "UPDATE_PKG"
    public string SchemaVersion { get; set; } = "1.0";
    public string BusinessCode { get; set; } = string.Empty;
    public DateTime TimestampUtc { get; set; } = DateTime.UtcNow;
    public string EncryptedPayloadBase64 { get; set; } = string.Empty; // AES-256-GCM cipher
    public string NonceBase64 { get; set; } = string.Empty; // 12 bytes IV
    public string TagBase64 { get; set; } = string.Empty; // 16 bytes auth tag
    public string WrappedKeyBase64 { get; set; } = string.Empty; // AES key wrapped with RSA
    public string RsaSignatureBase64 { get; set; } = string.Empty; // RSA-4096 SHA256 signature
}

/// <summary>
/// Signed License Renewal Payload (.lic)
/// </summary>
public class LicenseRenewalPayload
{
    public string LicenseId { get; set; } = Guid.NewGuid().ToString("N");
    public string BusinessCode { get; set; } = string.Empty;
    public SubscriptionTier Plan { get; set; } = SubscriptionTier.Basic;
    public DateTime IssuedDateUtc { get; set; } = DateTime.UtcNow;
    public DateTime ExpiryDateUtc { get; set; }
    public int GracePeriodDays { get; set; } = 7;
    public int MaxUsers { get; set; } = 5;
    public int MaxBranches { get; set; } = 1;
    public int MaxProducts { get; set; } = 10000;
    public BusinessType? BusinessType { get; set; }
    public List<string> EnabledModules { get; set; } = new();
    public string Signature { get; set; } = string.Empty;
}
